// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNCc6vVdXxxKV6AqvavqgtNcxmorakos',
    appId: '1:740210366983:web:71cedeb6a7a868363be8a2',
    messagingSenderId: '740210366983',
    projectId: 'fruit-hub-16436',
    authDomain: 'fruit-hub-16436.firebaseapp.com',
    storageBucket: 'fruit-hub-16436.firebasestorage.app',
    measurementId: 'G-2GVGDWZR6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDHDAHpnKsMlqDGM_J8LbaCd3vekR-4mI',
    appId: '1:740210366983:android:cb41404445f7e2b93be8a2',
    messagingSenderId: '740210366983',
    projectId: 'fruit-hub-16436',
    storageBucket: 'fruit-hub-16436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk0_jcdTZhW7YHwqysOUfgPvjnkkykkaU',
    appId: '1:740210366983:ios:b714fa7b8485772f3be8a2',
    messagingSenderId: '740210366983',
    projectId: 'fruit-hub-16436',
    storageBucket: 'fruit-hub-16436.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk0_jcdTZhW7YHwqysOUfgPvjnkkykkaU',
    appId: '1:740210366983:ios:b714fa7b8485772f3be8a2',
    messagingSenderId: '740210366983',
    projectId: 'fruit-hub-16436',
    storageBucket: 'fruit-hub-16436.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWNCc6vVdXxxKV6AqvavqgtNcxmorakos',
    appId: '1:740210366983:web:8e024d414cbb0e5f3be8a2',
    messagingSenderId: '740210366983',
    projectId: 'fruit-hub-16436',
    authDomain: 'fruit-hub-16436.firebaseapp.com',
    storageBucket: 'fruit-hub-16436.firebasestorage.app',
    measurementId: 'G-QBD0KJLPLR',
  );
}
